version: '3'
services:
  service-a:
    build:
      context: ./service-A
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  service-b:
    build:
      context: ./service-B # Correct the path if necessary
      dockerfile: Dockerfile
    ports:
      - 3002:3002

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - service-a
      - service-b
